version: '3.3'
services:
  web:
    container_name: schulNetz-Grades
    build: .
    pull_policy: build
    restart: unless-stopped
    env_file:
      - stack.env
    labels:
      - com.centurylinklabs.watchtower.enable=false
