version: '3.3'
services:
  web:
    container_name: schulNetz-Grades
    image: ghcr.io/lela810/schulnetz-grades:main
    restart: unless-stopped
    env_file:
      - stack.env
    labels:
      - com.centurylinklabs.watchtower.enable=false
