version: '3.3'
services:
  schulNetz-Grades:
    build: .
    depends_on:
      - mongodb
    networks:
      - schulnetz-net
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  mongodb:
    image: mongo:4.4.10
    environment:
      - MONGO_INITDB_DATABASE=schulNetz-grades
    volumes:
      - ./db:/data/db
    networks:
      - schulnetz-net
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
