version: '3.3'
services:
  web:
    container_name: schulNetz-Grades
    volumes:
      - ./archive:/app/archive
    build: .
    restart: unless-stopped
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.10
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=schulNetz-grades
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
