version: '3.3'
services:
  web:
    container_name: schulNetz-Grades
    build: .
    restart: unless-stopped
    env_file:
      - fileName: ./.env
    depends_on:
      - mongodb
    environment:
      - PROD=false
    network_mode: host
  mongodb:
    image: mongo:4.4.10
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=schulNetz-grades
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    network_mode: host
